### ISSUE TITLE
[Bug]: start_date not working

### ISSUE THREAD

**Issue by tkabt06** [alexpfau/calendar-card-pro#102]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

This function doesnt work for me 

### Expected Behavior

Calendar still starts this day and the code changes itself 
from start_date: '2025-06-16'
to start_date: "2025-06-16"

### Steps To Reproduce

..

### Card Configuration

```yaml
type: custom:calendar-card-pro
title: Semesterveckor
entities:
  - entity: calendar.familjen
    accent_color: "#FFFACD"
  - entity: calendar.tks_kalender
    accent_color: "#90EE90"
  - entity: calendar.isabell_tegnemo
    accent_color: "#FFC0CB"
  - entity: calendar.helgdagar_i_sverige
    accent_color: "#D3D3D3"
show_time: true
show_location: true
show_single_allday_time: false
show_empty_days: true
day_spacing: 6px
event_spacing: 2px
start_date: "2025-06-16"
days_to_show: 60
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: 
- Home Assistant Version: 
- Calendar Card Pro Version: 2.0
- Device Type:
```
