### ISSUE TITLE
[Bug]: Country Not Being Stripped

### ISSUE THREAD

**Issue by roblombardo** [alexpfau/calendar-card-pro#116]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

remove_location_country: true does not appear to be working. This is from a google calendar, but the data entry was done and is synced from Apple calendar. I don't see why this would matter, but that is the condition.

![Image](https://github.com/user-attachments/assets/894a2cd9-218b-48fa-8b91-f5fe1c5be69e)

### Expected Behavior

I would expect the country to be removed when displayed on the card.

### Steps To Reproduce

1) Add calendar card pro to dashboard.
2) configure with yaml below.
3) Countries still appear in event column.

![Image](https://github.com/user-attachments/assets/779097f6-9fdd-48bf-bb60-8969919badbd)

### Card Configuration

```yaml
type: custom:calendar-card-pro
entities:
  - entity: calendar.family
    accent_color: "#f7a8bb"
  - entity: calendar.janas_personal
    accent_color: "#0072c5"
  - entity: calendar.robs_personal
    accent_color: "#2bac00"
day_separator_width: 2px
day_separator_color: "#2c2c2c"
event_background_opacity: 0
vertical_line_width: 3px
days_to_show: 30
show_location: true
remove_location_country: true
time_24h: false
card_mod:
  style: |
    ha-card {
      background: transparent !important;
      border: solid 2px #2c2c2c;
      height: 316px !important;
      }
```

### Calendar Entity State

```yaml
# This is the family calendar 
message: Climbing Comp. Truckee
all_day: true
start_time: 2025-03-29 00:00:00
end_time: 2025-03-30 00:00:00
location: Truckee, CA
United States
description: 
offset_reached: false
friendly_name: Family Calendar
supported_features: 3
```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: Firefox 136.0.2
- Home Assistant Version: HAOS 15.0, 2025.3.4
- Calendar Card Pro Version: 2.1.2
- Device Type: Beelink S12 Pro, bare metal
```
