### ISSUE TITLE
[Bug]: Advanced Filtering Techniques not working for me

### ISSUE THREAD

**Issue by dg9bew** [alexpfau/calendar-card-pro#125]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

I tried to configure different entries from one calendar to be shown in different styles, like you described in 'Advanced Filtering Techniques'.

Outcome: 
![Image](https://github.com/user-attachments/assets/73b6037f-0f3d-4f31-b083-b2cbb18fbe2c)
The entries are duplicated and only the style defined in the firs entry is used.

If i put a third entry with another different allowlist, all items are shown 3 times.

If i put onle one entity in the configuration, it's working fine for the entry in the allowlist.

### Expected Behavior

Every item in the calendar should be displayed once, with the matching style.

### Steps To Reproduce

1. Add Calendar Card Pro
2. Have calendar with at least 2 items in the next 2 weeks
3. apply configuration 
4. look at result

### Card Configuration

```yaml
type: custom:calendar-card-pro
title: Kalender
entities:
  - entity: calendar.abfallkalender
    allowlist: Restmüll
    label: mdi:trash-can
    accent_color: grey
    show_location: false
    show_time: false
  - entity: calendar.abfallkalender
    allowlist: Wertstofftonne
    label: mdi:recycle
    accent_color: yellow
    show_location: false
    show_time: false 
days_to_show: 14
show_location: true
show_week_numbers: iso
week_separator_width: 2px
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: Firefox 136.0.4 (aarch64)
- Home Assistant Version: 
`Core 2025.3.4
Supervisor 2025.03.3
Operating System 15.0
Frontend 20250306.0`
- Calendar Card Pro Version: 2.2.0
- Device Type: Macbook
```

**Comment by alexpfau** [comment]
What does it look like with only this?

```yaml
type: custom:calendar-card-pro
title: Kalender
entities:
  - entity: calendar.abfallkalender
    allowlist: Restmüll
    label: mdi:trash-can
    accent_color: grey
    show_location: false
    show_time: false
```
