### ISSUE TITLE
[Bug]: past event label.

### ISSUE THREAD

**Issue by andyblac** [alexpfau/calendar-card-pro#129]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

when an event has has past, and you set to show past events, the label is no longer dimmer colour. this used to work prior to 2.2 update.

### Expected Behavior

when the event time has elapsed the label should go a dimmer brightness.

### Steps To Reproduce

add an a calendar to config, and allow past events to show.

### Card Configuration

```yaml
- type: custom:calendar-card-pro
        title: "Upcoming Events"
        entities:
          - entity: calendar.daily
        days_to_show: 2
        max_events_to_show: 5
        show_past_events: true
        event_font_size: "16px"
        time_font_size: "14px"
        time_icon_size: "16px"
        show_location: true
        event_background_opacity: 10
        vertical_line_width: 5px
        event_spacing: 5px
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: Safari 18.3.1
- Home Assistant Version: 2025.3.4
- Calendar Card Pro Version: 2.2
- Device Type: MacOS
```
