### ISSUE TITLE
[Feature]: filter based on all-day events

### ISSUE THREAD

**Issue by syst3x** [alexpfau/calendar-card-pro#132]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've verified this feature isn't already available in the configuration options
- [x] I've searched existing issues to verify this hasn't already been requested

### Is your feature request related to a problem?

I'd like to be able to use a single calendar but display all-day events in a different color/color accent than timed events. This would require being able to filter based on whether an event is all-day or not.

### Describe the solution you'd like

Add an additional filter option for all-day events (both include and exclude).

### Example use case

```
entities:
  - entity: calendar.family
    allowlist: all-day # Only show all-day events
    accent_color: gray
  - entity: calendar.family
    blocklist: all-day # do not show all-day events
    accent_color: blue
```
