### ISSUE TITLE
[Bug]: Setting a CSS variable as an `accent_color` does not apply the color to the event background

### ISSUE THREAD

**Issue by MathisP75** [alexpfau/calendar-card-pro#135]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

The background remains blue if a CSS color is provided, but the vertical line color changes correctly.
![Image](https://github.com/user-attachments/assets/a17986ba-8880-41a7-a12f-f5c69b3de029)

### Expected Behavior

The correct accent color should be applied.

### Steps To Reproduce

1. Set `accent_color: var(--red-color)` on a calendar entry
2. Notice the background color is not red

### Card Configuration

```yaml
type: custom:calendar-card-pro
entities:
  - entity: calendar.ets_hiver_2025
    accent_color: var(--red-color)
  - entity: calendar.transport
    accent_color: red
  - entity: calendar.mathispaquet362_gmail_com
    accent_color: cyan
  - entity: calendar.rdv
    accent_color: yellow
days_to_show: 1
show_location: true
day_font_size: 20px
weekday_font_size: 13px
month_font_size: 11px
show_month: false
event_spacing: 6px
vertical_line_width: 4px
date_vertical_alignment: middle
event_background_opacity: 25
tap_action:
  action: expand
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: Firefox/Chrome (doesn't matter here)
- Home Assistant Version: 2025.4.0b1
- Calendar Card Pro Version: 2.1.2
- Device Type: Laptop, phone, Raspberry Pi
```
