### ISSUE TITLE
[Bug]: Filtering multiple words in one entity

### ISSUE THREAD

**Issue by pedroRSL** [alexpfau/calendar-card-pro#136]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

When I filter one entity twice to filter out the words "work" and "salary" I get good results: I see both events but they all have the same color and label as the first filter.  The "salary" event is a full day event and the work event sometimes covers 2 days (shift work).

### Expected Behavior

  Show only salary:

  - entity: calendar.work
    allowlist: SALARY
    label: 💰
    accent_color: "#ff3300"
    color: "#ff3300"

show the rest (here I only have the words "work" in the calendar):

  - entity: calendar.work
    blocklist: SALARY
    label: ⚒
    accent_color: "#1e88e5"
    color: "#1e88e5"

as a result of these 2 filters I see all events (work and salary) in red with a money symbol

### Steps To Reproduce

As above, setting multiple filters for the same calendar results in it being displayed with the same colors and labels as the first filter.

### Card Configuration

```yaml
type: custom:calendar-card-pro
days_to_show: 15
show_location: true
entities:
  - entity: calendar.work
    allowlist: SALARY
    label: 💰
    accent_color: "#ff3300"
    color: "#ff3300"
  - entity: calendar.work
    blocklist: SALARY
    label: ⚒
    accent_color: "#1e88e5"
    color: "#1e88e5"
filter_duplicates: true
event_background_opacity: 10
vertical_line_width: 5px
event_spacing: 8px
week_separator_width: 1px
week_separator_color: "#03a9f450"
month_separator_width: 1.5px
month_separator_color: var(--secondary-text-color)
day_separator_width: 1px
day_separator_color: "#333333"
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
Phone Samsung S24Ultra (android companion app - latest version), tablet Samsung A9 (android companion app - latest version), PC (windows 11 chrome - latest version)
```
