### ISSUE TITLE
[Bug]: Automatically get date for start-date

### ISSUE THREAD

**Issue by ReadThinkBuild** [alexpfau/calendar-card-pro#137]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

I have not been able to get start_date working with anything beyond "today" and "YYYY-MM-DD".  I have tried:
- tomorrow
- '{{ (now() + timedelta(days=1)).strftime("%Y-%m-%d") }}'
- {{(as_timestamp(now())+ (86400)) | timestamp_custom("%Y-%m-%d")}}

Both formulas show tomorrows date in developer tools - template. But when added to the card, it continues to show todays events.

### Expected Behavior

I would like to use states to automatically get the right day in the card. 

### Steps To Reproduce

1. Add the calendar card to dashboard
2. Configure with these settings:
3. `type: custom:calendar-card-pro
entities:
  - entity: calendar.werk
    label: 💼
    accent_color: purple
start_date: "{{(as_timestamp(now())+ (86400)) | timestamp_custom(\"%Y-%m-%d\")}}"
`

### Card Configuration

```yaml
`type: custom:calendar-card-pro
entities:
  - entity: calendar.werk
    label: 💼
    accent_color: purple
start_date: "{{(as_timestamp(now())+ (86400)) | timestamp_custom(\"%Y-%m-%d\")}}"
`
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: Brave
- Home Assistant Version: 2025.3.4
- Calendar Card Pro Version: 2.2.1
- Device Type: laptop
```
