### ISSUE TITLE
[Bug]:  Events from different calendars gets sorted across other calendars.

### ISSUE THREAD

**Issue by droidgren** [alexpfau/calendar-card-pro#138]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

Using v2.2.1
It seems that whole-day events from different calendar get sorted across other calendars.

This make events jump around from day to day.  
**As default**, events should always appear from the order the calendar entity list defined.

There is no problem that events get sorted within its own calendar, but **should not do** do across others.

```
Example  If have defined calendars this order
- Calendar A 
- Calendar B


It should display event this way

Calendar A
- Event E2
- Event E3
- Event E4
Calendar B
- Event E1


And not like this

Calendar B
 - Event E1
Calendar A
 - Event E2
 - Event E3
 - Event E4
```

### Expected Behavior

Events should always appear from the order the calendar entity list defined.

### Steps To Reproduce

Add multiple calendars with whole day events and look at the results

### Card Configuration

```yaml
type: custom:calendar-card-pro
entities:
  - entity: calendar.food
    label: 🍽️
    accent_color: orange
  - entity: calendar.common
    label: 👨‍👩‍👦
  - entity: calendar.2good2know
  - entity: calendar.3holidays
    accent_color: tomato
days_to_show: 17
day_separator_width: 0px
max_events_to_show: 10
show_single_allday_time: false
show_week_numbers: iso
show_current_week_number: true
first_day_of_week: monday
week_separator_width: 1px
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version:  Chrome
- Home Assistant Version:  2025.3.4
- Calendar Card Pro Version:  2.2.1
- Device Type: Computer
```
