### ISSUE TITLE
[Bug]: Multiple cards on screen share settings

### ISSUE THREAD

**Issue by thatwebagency** [alexpfau/calendar-card-pro#143]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

i have a dashboard with a vertical stack containing 2 different calendar cards. when i change settings on each they seem to share these settings.

### Expected Behavior

I hoped i could set the first instance to start and end date today so i can show todays events and have a second calendar with heading with Upcoming Events.

### Steps To Reproduce

add a vertical stack with 2 calendar cards. settings start and end date to the first calendar works, but if i try to add these settings to the second calendar the first one begins using these settings instead.

### Card Configuration

```yaml
card:
          type: vertical-stack
          cards:
            - type: custom:calendar-card-pro
              title: Whats On Today
              entities:
                - entity: calendar.family
                  color: '#e63946'
              start_date: "today"
              end_date: "today"
              days_to_show: 0
              max_events_to_show: 5
              max_height: 400px
              show_location: true
              show_past_events: true
              background_color: transparent
              card_mod:
                style: |
                  ha-card {
                    border-radius: 0;
                    border: none;
                    box-shadow: none;
                    background: transparent;
                  }
            - type: custom:calendar-card-pro
              title: Upcoming Events
              entities:
                - entity: calendar.family
                  color: '#e63946'
              start_date: "today+1"
              days_to_show: 7
              max_events_to_show: 5
              max_height: 400px
              show_location: true
              background_color: transparent
              card_mod:
                style: |
                  ha-card {
                    border-radius: 0;
                    border: none;
                    box-shadow: none;
                    background: transparent;
                  }
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: any
- Home Assistant Version: 2025.14 OS 15.1
- Calendar Card Pro Version: V2 latest
- Device Type: any
```
