### ISSUE TITLE
[Bug]: Scrollbar always showing

### ISSUE THREAD

**Issue by martinsheldon** [alexpfau/calendar-card-pro#146]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

After updating to 2.3.0 the scrollbar always shows even when not hovering over the card.
Same for both Chrome and Firefox

### Expected Behavior

Scrollbar only to show when hovering over with the cursor

### Steps To Reproduce

Add calendar, config height and enough events to enable scrollbar.

![Image](https://github.com/user-attachments/assets/10216004-de6c-4397-bcfd-1ce7290356b9)

### Card Configuration

```yaml
type: custom:calendar-card-pro
weekend_weekday_color: "#E67C73"
weekend_day_color: "#E67C73"
weekend_month_color: "#E67C73"
day_separator_width: 1px
show_countdown: true
day_separator_color: "#9E9E9E"
week_separator_width: 2px
week_separator_color: "#BDBDBD"
event_font_size: 16px
show_week_numbers: iso
show_current_week_number: true
first_day_of_week: monday
days_to_show: 365
language: nb
max_events_to_show: 8
height: 470px
show_empty_days: false
show_past_events: true
date_vertical_alignment: top
show_time: true
show_single_allday_time: false
entities:
  - entity: calendar.aktiviteter
    accent_color: "#4caf50"
    color: "#4caf50"
    label: 🎭
    blocklist: Home Assistant Release Party
  - entity: calendar.aktiviteter
    accent_color: "#2196f3"
    color: "#2196f3"
    label: \local\Graphics\Common\HA.png
    allowlist: Home Assistant Release Party
  - entity: calendar.padel
    label: 🥅
    accent_color: "#ffeb3b"
    color: "#ffeb3b"
  - entity: calendar.ferier
    accent_color: "#6f42c1"
    color: "#6f42c1"
    label: 🛫
  - entity: calendar.nicolai_visiting
    accent_color: "#ff9800"
    color: "#ff9800"
    label: 👨‍👩‍👦
  - entity: calendar.fredrikstad_fk
    accent_color: "#ffffff"
    color: "#ffffff"
    label: \local\Graphics\Common\FFK.png
    entities: null
  - entity: calendar.liverpool_fc_supporters_club_norway
    accent_color: "#f44336"
    color: "#f44336"
    label: \local\Graphics\Common\LFC.png
    allowlist: Liverpool
event_background_opacity: 0
vertical_line_width: 5px
event_spacing: 4px
tap_action:
  action: expand
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: Chrome and Firefox
- Home Assistant Version: 2025.04
- Calendar Card Pro Version: 2.3.0
- Device Type: PC(?)
```
