### ISSUE TITLE
[Bug]: Google Calendar Whole Day events that span multiple days are not shown

### ISSUE THREAD

**Issue by smarthomejunkie** [alexpfau/calendar-card-pro#16]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

Great card! The only thing I've noticed is that Whole Day events (from Google Calendar) that span multiple days are not shown.

### Expected Behavior

Whole Day events are shown.

### Steps To Reproduce

Just add a whole day event that spans multiple days to the calendar that you show in the calandar-card-pro.

### Card Configuration

```yaml
type: custom:calendar-card-pro
entities:
  - calendar.my_gmail_calendar
days_to_show: 3
show_location: true
visibility:
  - condition: screen
    media_query: "(min-width: 768px)"
```

### Calendar Entity State

```yaml
on

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: Chrome 133.0.6943.142
- Home Assistant Version: 2025.3.3
- Calendar Card Pro Version: v1.0.0.
- Device Type: Desktop and Tablet
```

**Comment by alexpfau** [comment]
First of all, thanks for your feedback @smarthomejunkie! Highly appreciated!

I am struggling to reproduce your issue, as multi-day all-day events from Google Calendar do show up for me.

Does your multi-day all-day event show in the list when you run dev tools > actions > calendar.get_events?

Here is an example of what I get returned for my test calendar:
```
calendar.calendar_card_pro_work:
  events:
    - start: "2025-03-17"
      end: "2025-03-19"
      summary: Test 2-day all-day event
```

And here is how I see it in my calendar card:
<img width="488" alt="Image" src="https://github.com/user-attachments/assets/3d295553-0136-490e-a1e2-5b736464b0c2" />

with config:
```
type: custom:calendar-card-pro
entities:
  - calendar.calendar_card_pro_work
days_to_show: 1
```

Can you please double check if the issue persists for you, if the respective event actually does show up in HA dev tools, and provide the output your get there for the event?

**Comment by smarthomejunkie** [comment]
Hi Alex,
I do see results in the developer tools. Maybe it's because the event started in the past?

![Image](https://github.com/user-attachments/assets/d0d57e31-3ffb-4128-bddf-4d4cf05db94e)

The dashboard shows:

![Image](https://github.com/user-attachments/assets/4b495cf2-9c0d-4247-8b9f-17cbad7f7d9c)

The yaml is:
```
type: custom:calendar-card-pro
entities:
  - entity: calendar.smarthomejunkie_gmail_com
    color: "#457b9d"
days_to_show: 3
show_location: true
refresh_interval: 1
tap_action:
  action: expand
visibility:
  - condition: screen
    media_query: "(min-width: 768px)"
```
