### ISSUE TITLE
[Bug]: Sideways scrollbar showing when hovering over calendar

### ISSUE THREAD

**Issue by martinsheldon** [alexpfau/calendar-card-pro#162]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

Sideways scroll bar showing when hovering over the calendar. Same for both Chrome and Firefox

![Image](https://github.com/user-attachments/assets/26c7f001-2ed4-4abe-b86d-3525cf6c70f8)

### Expected Behavior

Sideways scrollbar is not needed

### Steps To Reproduce

Add calendar to dashboard, make sure there are more events than available space on the calendar, hover over with the cursor

### Card Configuration

```yaml
type: custom:calendar-card-pro
split_multiday_events: false
show_progress_bar: true
progress_bar_color: "#03a9f4"
progress_bar_height: 10px
progress_bar_width: 60px
today_indicator: pulse
today_weekday_color: "#f44336"
today_day_color: "#f44336"
today_month_color: "#f44336"
weekend_weekday_color: "#E67C73"
weekend_day_color: "#E67C73"
weekend_month_color: "#E67C73"
day_separator_width: 1px
show_countdown: true
day_separator_color: "#9E9E9E"
week_separator_width: 2px
week_separator_color: "#BDBDBD"
event_font_size: 16px
show_week_numbers: iso
show_current_week_number: true
first_day_of_week: monday
days_to_show: 365
language: nb
max_events_to_show: 6
height: 470px
show_empty_days: false
show_past_events: true
show_time: true
show_single_allday_time: false
entities:
  - entity: calendar.aktiviteter
    accent_color: "#4caf50"
    color: "#4caf50"
    label: 🎭
    blocklist: Home Assistant Release Party
  - entity: calendar.aktiviteter
    accent_color: "#2196f3"
    color: "#2196f3"
    label: \local\Graphics\Common\HA.png
    allowlist: Home Assistant Release Party
  - entity: calendar.padel
    label: 🥅
    accent_color: "#ffeb3b"
    color: "#ffeb3b"
  - entity: calendar.ferier
    accent_color: "#6f42c1"
    color: "#6f42c1"
    label: 🛫
  - entity: calendar.nicolai_visiting
    accent_color: "#ff9800"
    color: "#ff9800"
    label: 👨‍👩‍👦
  - entity: calendar.fredrikstad_fk
    accent_color: "#ffffff"
    color: "#ffffff"
    label: \local\Graphics\Common\FFK.png
    allowlist: Fredrikstad -
  - entity: calendar.fredrikstad_fk
    accent_color: "#607d8b"
    color: "#607d8b"
    label: \local\Graphics\Common\FFK.png
    allowlist: "- Fredrikstad"
  - entity: calendar.liverpool_fc_supporters_club_norway
    accent_color: "#f44336"
    color: "#f44336"
    label: \local\Graphics\Common\LFC.png
    allowlist: Liverpool
event_background_opacity: 0
vertical_line_width: 5px
event_spacing: 4px
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: Chrome & Firefox
- Home Assistant Version: 2025.4
- Calendar Card Pro Version: 2.4
- Device Type: PC
```
