### ISSUE TITLE
[Bug]: All day Event: show_single_allday_time not working.

### ISSUE THREAD

**Issue by NicoDeBelder** [alexpfau/calendar-card-pro#170]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

All day event still shows start and end time despite "show_single_allday_time: false".

Extra info: Apple Calendar (I know they kinda use custom formatting).

### Expected Behavior

All day label.

### Steps To Reproduce

Version 2.4.1
Cache cleared.

### Card Configuration

```yaml
type: custom:calendar-card-pro
entities:
  - entity: calendar.ical_home
    accent_color: "#1e88e5"
  - entity: calendar.ical_komma_board
    color: IndianRed
    accent_color: IndianRed
language: nl
days_to_show: 14
event_background_opacity: 15
show_single_allday_time: false
max_events_to_show: 10
show_past_events: false
show_end_time: false
show_location: false
today_indicator: true
show_countdown: true
tap_action:
  action: expand
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
Firefox, Arc, Chromium all have the same behavior.
```

### Additional Information

![Image](https://github.com/user-attachments/assets/a9e163b1-5373-479d-a110-563075a861e7)

Raw iCal data:
BEGIN:VEVENT
DTSTART;VALUE=DATE:20250417
DTEND;VALUE=DATE:20250418
SUMMARY:Franky Licenties
UID:F5E29B15-F661-445E-980A-DD82EF7272E8
SEQUENCE:0
DTSTAMP:20250407T102909Z
CREATED:20250407T102833Z
LAST-MODIFIED:20250407T102854Z
END:VEVENT

HA event attributes:
<img width="557" alt="Image" src="https://github.com/user-attachments/assets/2ff98022-52dd-4623-a998-ababb53b9df2" />
