### ISSUE TITLE
[Bug]: Split Multiday Events does not work for Google Agenda multiday events that started in the past

### ISSUE THREAD

**Issue by smarthomejunkie** [alexpfau/calendar-card-pro#171]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

I've added the line ``split_multiday_events: true``, but the multiday event is only shown today

The multiday event started in the past and continues for the rest of this week.
It's an event from a Google calendar.

### Expected Behavior

The multiday event should be shown on each day that the vent is planned for.

### Steps To Reproduce

Add the line ``split_multiday_events: true`` to the YAML.

### Card Configuration

```yaml
type: custom:calendar-card-pro
entities:
  - entity: calendar.cal1
    accent_color: "#1e88e5"
  - entity: calendar.cal2
    accent_color: "#43a047"
  - entity: calendar.cal3
    accent_color: "#D170DE"
    label: 👨‍⚕️
today_indicator: true
show_countdown: true
show_progress_bar: true
split_multiday_events: true
event_background_opacity: 15
show_empty_days: true
refresh_on_navigate: false
show_single_allday_time: false
title: 📅 Upcoming events
date_vertical_alignment: middle
row_spacing: 10px
vertical_line_width: 5px
horizontal_line_color: "#343434"
days_to_show: 3
show_location: true
refresh_interval: 15
max_events_to_show: 8
tap_action:
  action: expand
visibility:
  - condition: screen
    media_query: "(min-width: 768px)"
```

### Calendar Entity State

```yaml
State is "on"

Attributes:

message: Daan bij mij
all_day: true
start_time: "2025-04-07 00:00:00"
end_time: "2025-04-14 00:00:00"
location: ""
description: ""
offset_reached: false
friendly_name: cal1
supported_features: 3
```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: Chrome Version 134.0.6998.178 (Official Build) (64-bit)
- Home Assistant Version: 2025.4.1
- Calendar Card Pro Version: 2.4.1
- Device Type: Desktop
```
