### ISSUE TITLE
[Bug]: all day events of the day are in gray

### ISSUE THREAD

**Issue by jonicunha** [alexpfau/calendar-card-pro#174]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

Since the latest versions, the all day events of the day are appearing in gray.

![Image](https://github.com/user-attachments/assets/3d341928-5dd3-408b-ab49-49f90c4b4877)

Is it possible to put the all day events of the day in blank like the days following today as it was in the past?

I have already tried to make the card configuration as simple as possible but the situation remains:

```
type: custom:calendar-card-pro
title: Upcoming events
entities:
  - entity: calendar.facebook_birthdays_fb2cal
    accent_color: "#ff6c92"
```

### Expected Behavior

All day events of the day with blank text

### Steps To Reproduce

NA

### Card Configuration

```yaml
type: custom:calendar-card-pro
title: Upcoming events
entities:
  - entity: calendar.family
    accent_color: yellow
  - entity: calendar.facebook_birthdays_fb2cal
    accent_color: "#ff6c92"
  - entity: calendar.fases_da_lua
    accent_color: green
  - entity: calendar.feriados_em_portugal
    accent_color: "#c2ffb3"
  - entity: calendar.jonicunha_gmail_com
    accent_color: "#ff6c92"
compact_days_to_show: 1
compact_events_to_show: 10
days_to_show: 3
event_background_opacity: 20
today_indicator: true
today_indicator_color: white
time_24h: true
show_month: true
show_location: false
remove_location_country: true
vertical_line_width: 5px
event_spacing: 6px
title_font_size: 26px
weekday_font_size: 14px
day_font_size: 32px
month_font_size: 12px
event_font_size: 14px
time_font_size: 12px
location_font_size: 12px
time_location_icon_size: 14px
tap_action:
  action: expand
hold_action:
  action: call-service
  service: automation.trigger
  service_data:
    entity_id: automation.tablet_calendar
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: Version 135.0.7049.43 (Official Build) (64-bit)
- Home Assistant Version: core-2025.4.1
- Calendar Card Pro Version: 2.4.1
- Device Type:
```
