### ISSUE TITLE
[Bug]: Week separator is not inserted for all weeks

### ISSUE THREAD

**Issue by LiquidPT** [alexpfau/calendar-card-pro#175]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

I just added a week separator, and it gets inserted at the beginning of some weeks, but not all. I've tried this both with and without first_day_of_week set. 

### Expected Behavior

There should be a separator for every week. 

### Steps To Reproduce

Configure Calendar Card Pro with the week_separator_width and week_separator_color

### Card Configuration

```yaml
type: custom:calendar-card-pro
entities:
  - entity: calendar.liquidpt_family_room
    accent_color: "#003966"
    blocklist: garbage|recycling
    split_multiday_events: true
  - entity: calendar.pussycats
    accent_color: "#bf0077"
  - entity: calendar.liquidpt_f1_grand_prix
    accent_color: "#94ff4d"
    show_location: false
  - entity: calendar.liquidpt_us_holidays
    accent_color: "#69797e"
  - entity: calendar.liquidpt_possible_pussycat
    accent_color: "#bf0077"
days_to_show: 45
show_location: true
time_24h: false
show_end_time: false
show_event_highlight: true
date_vertical_alignment: top
background_color: transparent
event_font_size: 16px
event_background_opacity: 30
show_single_allday_time: false
show_past_events: false
today_indicator: true
first_day_of_week: monday
week_separator_width: 2px
week_separator_color: "#cccccc80"
grid_options:
  columns: 24
  rows: auto
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: Edge 135.0.3179.66 (latest)
- Home Assistant Version: 2024.04.1
- Calendar Card Pro Version: 2.4.1
- Device Type: Windows 11 PC
```

### Additional Information
There should be separators where each of the red arrows are

![Image](https://github.com/user-attachments/assets/e4f7645a-1667-40a8-82e7-e235b0512815)
