### ISSUE TITLE
[Bug]: days_to_show

### ISSUE THREAD

**Issue by albertosalogni** [alexpfau/calendar-card-pro#177]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

I've set days_to_show: 25 but it's only showing 15 days; I have appointments for the whole next month. EDIT: if i put more than 35 it shows the correct amount of days

### Expected Behavior

show correct number of days according to the parameter "days_to_show:"

### Steps To Reproduce

parameter "days_to_show:" works fine from 1 to 15 (i tried each number), if i write 16 or more it shows at maximum 15 days EDIT: if i put more than 35 it shows the correct amount of days

### Card Configuration

```yaml
type: custom:calendar-card-pro
title: CALENDARIO LABORATORIO
card_mod:
  style: |
    ha-card .header-container h1.card-header {
      width: 100%;
      text-align: center;
      float: none !important;
    }
title_font_size: 25px
title_color: "#8c92ac"
entities:
  - entity: calendar.calendario
    allowlist: ALBERTO
    label: 🏖️
    accent_color: "#008000"
  - entity: calendar.calendario
    allowlist: MARCO
    label: 🏝️
    accent_color: "#cd7f32"
  - entity: calendar.calendario
    allowlist: NICOLA
    label: 🏜️
    accent_color: "#fff600"
  - entity: calendar.calendario
    allowlist: DIEGO
    label: 🏞️
    accent_color: "#0047ab"
  - entity: calendar.calendario
    allowlist: Manutenzione
    label: 🔧
    accent_color: "#a52a2a"
  - entity: calendar.calendario
    allowlist: incontro
    label: 🗒️
    accent_color: "#8a2be2"
show_empty_days: true
days_to_show: 25
empty_day_color: orange
show_month: true
month_font_size: 10px
split_multiday_events: true
show_location: true
start_date: "-1"
show_week_numbers: iso
first_day_of_week: monday
week_number_font_size: 12px
week_number_background_color: "#03a9f450"
day_separator_width: 2px
day_separator_color: "#03a9f430"
week_separator_width: 3px
week_separator_color: "#03a9f480"
month_separator_width: 3px
month_separator_color: "#03a9f4"
weekend_weekday_color: "#E67C73"
weekend_day_color: "#E67C73"
weekend_month_color: "#E67C73"
today_indicator: ⭐
tap_action:
  action: expand
language: it
refresh_interval: 1
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: 
- Home Assistant Version: 
- Calendar Card Pro Version: 
- Device Type:
```
