### ISSUE TITLE
[Bug]: RTL languages

### ISSUE THREAD

**Issue by ntk9** [alexpfau/calendar-card-pro#179]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

the header of the card and the colors of the days are on the left side

### Expected Behavior

they need to be on the right

i upload this photo to show how it need to be 

[https://i.ibb.co/0NfyK8Z/Untitled-1sd.png](url)

### Steps To Reproduce

switch to rtl language in home assistant

### Card Configuration

```yaml
type: custom:calendar-card-pro
title: שלום
entities:
  - entity: calendar.holidays
    color: "#e63946"
days_to_show: 5
max_events_to_show: 5
show_location: true
language: he
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: 
- Home Assistant Version: 
- Calendar Card Pro Version: 
- Device Type:
```
