### ISSUE TITLE
[Bug]: Frameless example doens't work

### ISSUE THREAD

**Issue by Victorsoeby** [alexpfau/calendar-card-pro#180]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

The grey background is still visible even when following the example in the readme to get the frameless view. 

### Expected Behavior

The background disappears and the calender can be nicely put ontop of another background such as a picture card

### Steps To Reproduce

1. Did the HACS Installation (Recommended) from readme
2. Created local calender instance
3. Added calendar-card-pro with the frameless settings
4. Background is still there :(

### Card Configuration

```yaml
type: custom:calendar-card-pro
card_mod:
  style: |
    ha-card {
      border-radius: 0;
      border: none;
      box-shadow: none;
      background: transparent;
    }
entities:
  - entity: calendar.shared_calendar
    color: "#ff9800"
days_to_show: 5
max_events_to_show: 8
show_location: true
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: 
- Home Assistant Version: 
- Calendar Card Pro Version: 
- Device Type:
```

**Comment by alexpfau** [comment]
@Victorsoeby, thanks for your bug ticket. You may need an "!important" for background in card-mod to persist.

```yaml
type: custom:calendar-card-pro
card_mod:
  style: |
    ha-card {
      border-radius: 0;
      border: none;
      box-shadow: none;
      background: transparent !important;
    }
entities:
  - entity: calendar.shared_calendar
    color: "#ff9800"
days_to_show: 5
max_events_to_show: 8
show_location: true
```

Not really a bug in my code, but something to improve in my documentation to make the example more robust. I will update the ReadMe accordingly. Thank you!
