### ISSUE TITLE
[Bug]: days_to_show empty days not displaying

### ISSUE THREAD

**Issue by Merlyn42** [alexpfau/calendar-card-pro#189]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

I have the days to show set to 14 but it only shows until Friday(when I have an event). If I increase the days to show enough such that another event is within the window it will show until that event. I have show_empty_days: true

Effectively it will only show empty days if there is a non-empty day after it.
I have also played around with the start date and found the same behaviour.

### Expected Behavior

If show_empty_days is set to true it should show as many days as indicated by days_to_show regardless if they empty or not.

### Steps To Reproduce

Configure the calendar with show_empty_days: true and days_to_show to a value which would empty days at the end. 

### Card Configuration

```yaml
title: Family Schedule
type: custom:calendar-card-pro
entities:
  - calendar.my_calendar
  - calendar.l_l
days_to_show: 14
today_indicator: true
show_location: true
show_empty_days: true
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: Both Firefox and the companion app
- Home Assistant Version: 2025.4.1
- Calendar Card Pro Version: 2.4.1
- Device Type: Windows PC and Android
```

### Additional Information

This seems to match https://github.com/alexpfau/calendar-card-pro/issues/173 and https://github.com/alexpfau/calendar-card-pro/issues/177
