### ISSUE TITLE
[Bug]: Calendar Card Pro sometimes shows "No upcoming events" despite having entries

### ISSUE THREAD

**Issue by pluusla** [alexpfau/calendar-card-pro#192]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

The Calendar Card Pro sometimes displays "No upcoming events" even when there are scheduled events in the linked calendar. This seems to be a temporary issue, as the events appear after navigating away from the dashboard and then returning, or by switching views within Home Assistant.

### Expected Behavior

The calendar card should consistently display the upcoming events from the specified calendar (calendar.gemeinsamer_kalender) without showing "No upcoming events" when entries are present.

### Steps To Reproduce

While the exact steps to consistently reproduce this issue are unclear, it seems to occur sporadically. However, the following configuration is being used when the issue arises:

```yaml
type: custom:calendar-card-pro
entities:
  - calendar.gemeinsamer_kalender
days_to_show: 1
show_location: true
max_events_to_show: 5
title: Gemeinsame Termine
show_week_numbers: iso
show_current_week_number: true
refresh_on_navigate: false
show_countdown: true
show_progress_bar: true
refresh_interval: 15

### Card Configuration

```yaml
type: custom:calendar-card-pro
entities:
  - calendar.gemeinsamer_kalender
days_to_show: 1
show_location: true
max_events_to_show: 5
title: Gemeinsame Termine
show_week_numbers: iso
show_current_week_number: true
refresh_on_navigate: false
show_countdown: true
show_progress_bar: true
refresh_interval: 15
```

### Calendar Entity State

```yaml
**state:**
on

**attributes:**
message: Reiten
all_day: false
start_time: 2025-04-18 09:00:00
end_time: 2025-04-18 12:00:00
location: 
description: 
offset_reached: false
friendly_name: Gemeinsamer kalender
supported_features: 3
```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: latest Brave
- Home Assistant Version: 2025.4.2
- Calendar Card Pro Version: 2.4.1
- Device Type: Desktop Browser and Mobile
```

### Additional Information

![Image](https://github.com/user-attachments/assets/0c00b98c-2eff-48be-b2f7-e2f63a690415)

![Image](https://github.com/user-attachments/assets/36f7cd83-d238-4997-8584-463484b70198)
