### ISSUE TITLE
[Feature]: New option: highlightlist

### ISSUE THREAD

**Issue by mischpoke** [alexpfau/calendar-card-pro#195]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've verified this feature isn't already available in the configuration options
- [x] I've searched existing issues to verify this hasn't already been requested

### Is your feature request related to a problem?

Cheers Alex!

I would like to keep every event visible while still being able to visually flag a specific subset - for example birthdays, stand‑ups, or deadlines in the same calendar.

With the current options:

- allowlist: shows only the matched events but hides everything else.
- blocklist: hides the matched events entirely.

Neither lets me simply highlight matches and still display the rest of the calendar. 

A dedicated “decorate‑only” filter would solve this by letting me spotlight certain events without losing sight of the rest.

### Describe the solution you'd like

"**highlightlist**" a lightweight extension that fits naturally alongside **allowlist** and **blocklist** while leaving today’s behaviour 100 % intact.

New option: **highlightlist**
Matches stay visible, get styled, and do not block any other events. Think of it as “decorate‑only”.

How it’s applied (order of precedence)

1. blocklist – always hides matched events.
2. allowlist – whitelists matched events and hides everything else.
3. highlightlist – adds visuals to matched events but never hides anything.
4. Anything unmatched by the above just renders normally.

### Example use case

```
entities:
  # 🔎 1. Call out all team‑syncs in blue, but still show every event
  - entity: calendar.family
    highlightlist: 'stand‑up|sync|retro'  
    label: '👥'
    accent_color: '#1e88e5' 

  # 🎂 2. Spotlight family birthdays in pink
  - entity: calendar.family
    highlightlist: ['birthday', 'anniversary']
    label: '🎉'
    accent_color: '#e91e63'

  # 3. Nothing else filtered out – everything else just renders normally
  - entity: calendar.family
```

### Additional context

Benefits of a separate option:

- Zero breaking change – existing configs keep working.
- Clear mental model – three mutually‑exclusive verbs: allow, block, highlight.
- Composable – you can combine all three on the same entity if you really need to:

```
- entity: calendar.family
  blocklist: 'spam'
  allowlist: 'important|vip'
  highlightlist: 'gift|deadline'
```
