### ISSUE TITLE
[Bug]: Show empty day even if there are events

### ISSUE THREAD

**Issue by marc3k18** [alexpfau/calendar-card-pro#198]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

Show the date of the 25 empty but there is event in the calendar. In an other view, we can see it's working.

![Image](https://github.com/user-attachments/assets/27a9128c-4a38-4bd1-9e22-4e705a7a39c3)

![Image](https://github.com/user-attachments/assets/224cdaa8-8fe6-47f5-a7cc-e8c5925bab9a)

### Expected Behavior

Show the event?

### Steps To Reproduce

See configuration bellow

### Card Configuration

```yaml
type: custom:calendar-card-pro
title: null
entities:
  - entity: calendar
    accent_color: pink
    label: 🥳
  - entity: calendar
    blocklist: rendez-vous privé
    accent_color: orange
    label: 💼
  - entity: calendar
    accent_color: indigo
    label: 🧒
  - entity: calendar.canada_qc
    accent_color: yellow
    label: 🌴
  - entity: calendar.poubelle
    accent_color: brown
    label: 🗑
  - entity: calendar.recyclage
    accent_color: blue
    label: ♻️
  - entity: calendar.scolaire
    accent_color: yellow
    label: 🌴
  - entity: calendar.family
    blocklist: poubelles|recyclage
    accent_color: red
    label: 👪
  - entity: calendar
    accent_color: yellow
    label: 🏈
show_week_numbers: iso
show_current_week_number: false
first_day_of_week: monday
week_number_font_size: 12px
week_number_color: white
week_number_background_color: "#03a9f450"
me: false
show_empty_days: true
event_background_opacity: 30
show_location: true
language: fr
weekday_color: white
day_color: white
month_color: white
time_color: "#D3D3D3"
location_color: "#baf1ff"
vertical_line_width: 5px
vertical_line_color: "#baf1ff"
horizontal_line_width: 2px
horizontal_line_color: "#baf1ff80"
day_separator_width: 1px
day_separator_color: red
week_separator_width: 1px
week_separator_color: blue
month_separator_width: 1px
month_separator_color: yellow
day_spacing: 2px
event_spacing: 6px
max_events_to_show: 6
show_single_allday_time: false
show_countdown: true
tap_action:
  action: navigate
  navigation_path: "#full_calendrier"
card_mod:
  style: |
    ha-card {
      background-color: black !important; 
      border-radius: 30px !important;
      opacity: 65%;
    }

    /* Add subtle left border pulse animation */
    .day-table.today .event {
      border-left-width: 4px !important;
      transition: border-left-color 1s ease-in-out;
      animation: todayPulse 3s infinite alternate;
    }

    @keyframes todayPulse {
      from { border-left-color: var(--accent-color); }
      to { border-left-color: var(--primary-color); }
    }
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Home Assistant Version: 2025.4.3
- Calendar Card Pro Version: 2.4.5
- Device Type: Computer, Android and KioskBrowser
```
