### ISSUE TITLE
[Bug]:  Or it's me ? Card full width of the screen

### ISSUE THREAD

**Issue by acress1** [alexpfau/calendar-card-pro#202]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

Hi,

I believe I don't find any solution to display the calendar full width, I tried several things "columns: 4", I tried to change  
```
style: |
    div.event-content {
      grid-template-columns: 1fr auto; 
} 
```
with another value, etc.

I find nothing... :/
Does someone know ?

Thanks a lot,
cress

### Expected Behavior

I would have to put in my card a value "full width" and then the calendar would be fully displayed in width.

### Steps To Reproduce

1. In the Calendar Card, I would set up the value of full width to true, or something like that.

### Card Configuration

```yaml
type: custom:calendar-card-pro
entities:
  - entity: calendar.vacances
    accent_color: "#85C04A"
  - entity: calendar.antoine
    accent_color: "#E4D200"
  - entity: calendar.emma
    accent_color: "#AA81B8"
  - entity: calendar.echo_alpha
    accent_color: "#D3A265"
days_to_show: 15
show_empty_days: true
compact_events_to_show: 12
show_location: true
title: Calendrier
show_week_numbers: iso
show_current_week_number: true
week_number_background_color: "#1376B3"
week_number_color: "#FAFAFB"
week_number_font_size: 10px
event_spacing: 4px
date_vertical_alignment: middle
event_background_opacity: 6
show_countdown: true
show_progress_bar: true
progress_bar_color: "#749AC4"
week_separator_width: 1px
week_separator_color: "#03a9f450"
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: Firefox
- Home Assistant Version: 
- Calendar Card Pro Version: v.2.4.5
- Device Type:
```
