### ISSUE TITLE
[Bug]: week seperator requires week number

### ISSUE THREAD

**Issue by LiquidPT** [alexpfau/calendar-card-pro#209]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

If week number isn't specified, it shows (previously it didn't by default). If I say "none" for week number the the week seperator does not show. 

### Expected Behavior

You should be able to see the week seperator even without a week number

### Steps To Reproduce

1. Specify styles for a week seperator, but "none" for week number using the new config UX

### Card Configuration

```yaml
entities:
  - entity: calendar.liquidpt_us_holidays
    accent_color: "#69797e"
    show_location: false
  - entity: calendar.liquidpt_family_room
    accent_color: "#003966"
    blocklist: garbage|recycling
    split_multiday_events: true
  - entity: calendar.pussycats
    accent_color: "#bf0077"
  - entity: calendar.liquidpt_possible_pussycat
    accent_color: "#bf0077"
  - entity: calendar.liquidpt_f1_grand_prix
    accent_color: "#94ff4d"
    show_location: false
days_to_show: 60
compact_events_complete_days: false
show_empty_days: false
filter_duplicates: false
split_multiday_events: false
background_color: transparent
accent_color: "#03a9f4"
vertical_line_width: 2px
day_spacing: 10px
event_spacing: 4px
additional_card_spacing: 0px
first_day_of_week: monday
show_week_numbers: "null"
show_current_week_number: true
week_number_font_size: 12px
week_number_color: var(--primary-text-color)
week_number_background_color: "#03a9f450"
day_separator_width: 0px
day_separator_color: var(--secondary-text-color)
week_separator_width: 2px
week_separator_color: "#cccccc80"
month_separator_width: 0px
month_separator_color: var(--primary-text-color)
today_indicator: dot
today_indicator_position: 15% 50%
today_indicator_color: "#03a9f4"
today_indicator_size: 6px
date_vertical_alignment: top
weekday_font_size: 14px
weekday_color: var(--primary-text-color)
day_font_size: 26px
day_color: var(--primary-text-color)
show_month: true
month_font_size: 12px
month_color: var(--primary-text-color)
event_background_opacity: 30
show_past_events: false
show_countdown: false
show_progress_bar: false
progress_bar_color: var(--secondary-text-color)
progress_bar_height: calc(var(--calendar-card-font-size-time) * 0.75)
progress_bar_width: 60px
event_font_size: 16px
event_color: var(--primary-text-color)
empty_day_color: var(--primary-text-color)
show_time: true
show_single_allday_time: false
time_24h: false
show_end_time: false
time_font_size: 12px
time_color: var(--secondary-text-color)
time_icon_size: 14px
show_location: true
remove_location_country: false
location_font_size: 12px
location_color: var(--secondary-text-color)
location_icon_size: 14px
weather:
  position: date
  date:
    show_conditions: true
    show_high_temp: true
    show_low_temp: false
    icon_size: 14px
    font_size: 12px
    color: var(--primary-text-color)
  event:
    show_conditions: true
    show_temp: true
    icon_size: 14px
    font_size: 12px
    color: var(--primary-text-color)
  entity: weather.home
tap_action:
  action: none
hold_action:
  action: none
refresh_interval: 30
refresh_on_navigate: true
type: custom:calendar-card-pro
show_event_highlight: true
grid_options:
  columns: 24
  rows: auto
remove_location_country_selector: "false"
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: HA Android app 2025.4.3-full
- Home Assistant Version: 2025.4.4
- Calendar Card Pro Version: 3.0.0
- Device Type: Samsung Galaxy
```

### Additional Information

I should also point out there's a LOT more YAML than there was previously because all the defaults now have saved values. I would have thought that the YAML would have preserved the unspecified "defaultness" rather than saving today's default value and making that "chosen"
