### ISSUE TITLE
[Bug]: Weather not displaying for all days on card

### ISSUE THREAD

**Issue by njjerrysmith** [alexpfau/calendar-card-pro#213]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

Weather is only showing for 2 of 3 days on card in event position only.

![Image](https://github.com/user-attachments/assets/681e9740-3a75-401d-994a-6861929f703a)

### Expected Behavior

Weather to show for third day.

### Steps To Reproduce

1. Add card
2. Set to 3 days display current day
3. Enable weather, set position to event

### Card Configuration

```yaml
entities:
  - calendar.twins_home_games
compact_events_to_show: 3
show_empty_days: true
filter_duplicates: true
today_indicator: 🗓️
show_location: false
weather:
  position: event
  date:
    show_conditions: true
    show_high_temp: true
    show_low_temp: false
    icon_size: 14px
    font_size: 12px
    color: var(--primary-text-color)
  event:
    show_conditions: true
    show_temp: true
    icon_size: 14px
    font_size: 12px
    color: var(--primary-text-color)
  entity: weather.forecast_home
tap_action:
  action: navigate
  navigation_path: /calendar/
type: custom:calendar-card-pro
navigation_path: /calendar/
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: multiple (Apple Safari, Google Chrome, Mobile App)
- Home Assistant Version: 2025.5.1
- Calendar Card Pro Version: 3.0.2
- Device Type: multiple (Macbook Pro & iPhone Pro)
```
