### ISSUE TITLE
[Bug]: Unable to select Weather entity through GUI

### ISSUE THREAD

**Issue by mhoogenbosch** [alexpfau/calendar-card-pro#214]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

I'm unable to select a weather entity. Neither in a newly placed card and in my already excisting.

https://github.com/user-attachments/assets/16fef56c-0aa9-425b-b692-03cb5061f584

When entering it throught yaml code, it isn't able to save it.

As per thread: https://community.home-assistant.io/t/calendar-card-pro-a-beautiful-high-performance-calendar-card-for-home-assistant/863711/143

### Expected Behavior

Being able to select the entity.

### Steps To Reproduce

1. card to dashboard
2. default calendar entity
3. select weather
4. ... see movie

### Card Configuration

```yaml
entities:
  - calendar.birthdays
weather:
  position: date
  date:
    show_conditions: true
    show_high_temp: true
    show_low_temp: false
    icon_size: 14px
    font_size: 12px
    color: var(--primary-text-color)
  event:
    show_conditions: true
    show_temp: true
    icon_size: 14px
    font_size: 12px
    color: var(--primary-text-color)
type: custom:calendar-card-pro
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: Edge (Win 11)
- Home Assistant Version: 2025.5.0b5
- Calendar Card Pro Version: 3.0.2
- Device Type: Tried both iPhone as Windows 11
```
