### ISSUE TITLE
[Bug]: GUI dropdown not adding entities to yaml

### ISSUE THREAD

**Issue by dives11** [alexpfau/calendar-card-pro#217]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

Selecting a calendar entity  (birthdays, work schedule, etc.) from GUI drop down does not update the YAML and defaults to calendar:calendar entity when selected. Same goes for weather entities. The entity can be added manually by modifying the YAML.

Note: I have not tested this on previous versions yet.

### Expected Behavior

When "work schedule" calendar entity is selected from drop down, the entity should be added to YAML.

### Steps To Reproduce

1. Select "Add Calendar"
2. Select "***@gmail.com" entity from Entity drop down.
3. Unable to select calendar and defaults to calendar.calendar entity.

### Card Configuration

```yaml
entities:
  - entity: calendar.workschedule <--added manually
    label: 🚑 <--added via GUI
    color: "#324ea8" <--added via GUI
    accent_color: "#8f32a8" <--added via GUI
  - calendar.birthdays  <--added manually
  - calendar.****_gmail_com <--added via manually
  - entity: calendar.calendar <--added via GUI (supposed to be different entity)
day_separator_width: 1px <--added via GUI
week_separator_width: 1px <--added via GUI
today_indicator: glow <--added via GUI
weather:
  entity: weather.forecast_home <--added via manually
  position: both
  date:
    icon_size: 16px
    font_size: 14px
    color: "#3498db"
  event:
    show_conditions: false
    font_size: 13px
    color: var(--secondary-text-color)
type: custom:calendar-card-pro
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: Firfox 138.0.1 (64-bit)
- Home Assistant Version:  Core 2025.5.0
                           Supervisor 2025.04.1
                           Operating System 15.2
                           Frontend 20250507.0
- Calendar Card Pro Version: 3.0.2
- Device Type: Ubuntu KVM Virtual Server
```
