### ISSUE TITLE
[Bug]: Shaded Accent Backgrounds fail after 3.0.x

### ISSUE THREAD

**Issue by dml105** [alexpfau/calendar-card-pro#219]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

Some, but not all calendars will not shade when background shading is selected

### Expected Behavior

Setting event_background_opacity to 20% should change the background to be a transparent version of the accent color

### Steps To Reproduce

Several calendars do not work. 

### Card Configuration

```yaml
entities:
  - entity: calendar.holidays_in_united_states
    color: black
    accent_color: blue
    blocklist: ""
    show_time: false
    split_multiday_events: false
event_background_opacity: 30
weather:
  position: date
  date:
    show_conditions: true
    show_high_temp: true
    show_low_temp: false
    icon_size: 14px
    font_size: 12px
    color: var(--primary-text-color)
  event:
    show_conditions: true
    show_temp: true
    icon_size: 14px
    font_size: 12px
    color: var(--primary-text-color)
type: custom:calendar-card-pro
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: 
- Home Assistant Version: 
- Calendar Card Pro Version: 
- Device Type:
```
