### ISSUE TITLE
[Bug]: Incorrect Ukrainian translation

### ISSUE THREAD

**Issue by merlin-zaraza** [alexpfau/calendar-card-pro#223]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

Sunday is `Вс`:

<img width="520" alt="Image" src="https://github.com/user-attachments/assets/8a80bbd1-05c1-4b98-956d-dd6ea476d092" />

### Expected Behavior

Sunday is `Нд`

### Steps To Reproduce

1. Add calendar to see full week

### Card Configuration

```yaml
entities:
  - entity: calendar.home
    color: ""
    show_time: false
  - entity: calendar.family
    color: ""
  - entity: calendar.work
days_to_show: 7
show_empty_days: true
split_multiday_events: true
first_day_of_week: sunday
today_indicator: dot
show_countdown: true
time_24h: true
weather:
  position: date
  date:
    show_conditions: true
    show_high_temp: true
    show_low_temp: true
    icon_size: 14px
    font_size: 12px
    color: var(--primary-text-color)
  event:
    show_conditions: true
    show_temp: true
    icon_size: 14px
    font_size: 12px
    color: var(--primary-text-color)
  entity: weather.home
refresh_interval: 5
type: custom:calendar-card-pro
grid_options:
  columns: full
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: Zen Browser 1.12.3b
- Home Assistant Version: 2025.5.1
- Calendar Card Pro Version: 3.0.4
- Device Type: Laptop
```
