### ISSUE TITLE
[Bug]: Calendar event filtering applies to instances of the same calendar

### ISSUE THREAD

**Issue by Zerosignal84** [alexpfau/calendar-card-pro#228]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

We have a family calendar with some weekly reoccurring events that I do not want to show in the future until the existing event has completed.

I thought it would be possible to filter out the event using the allow/block list technique and then limit that instance of the calendar to show only 1 event at a time.

What seems to happen is that the first use of 'compact_events_to_show:' applies against all future instances of that calendar entry.

```
  - entity: calendar.familycalendar
    label: mdi:human-male-female-child
    show_location: true
    show_time: true
    split_multiday_events: false
    blocklist: Swimming Classes
    compact_events_to_show: 5
  - entity: calendar.familycalendar
    allowlist: Swimming Classes
    compact_events_to_show: 1
```

### Expected Behavior

What I would like or expected to see was only one instance of the "swimming classes" event in the schedule but with the 5 events taking priority over the 1 I still see all upcoming swimming classes.

The same appears to be true for show_time and show_location but I have not extensively tested that.

### Steps To Reproduce

1. add to calendarpro card to dashboard
2. use YAML below or similar
3. insert a reoccurring event in to your calendar
4. adjust YAML below for filtering.

### Card Configuration

```yaml
entities:
  - entity: calendar.familycalendar
    label: mdi:human-male-female-child
    show_location: true
    show_time: true
    split_multiday_events: false
    blocklist: Swimming Classes
    compact_events_to_show: 5
  - entity: calendar.familycalendar
    allowlist: Swimming Classes
    compact_events_to_show: 1
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: Edge
- Home Assistant Version: 2025.4.2
- Calendar Card Pro Version: 3.0.04
- Device Type: Windows
```

**Comment by alexpfau** [comment]
@Zerosignal84, thanks for you bug report! It's hard for me to reproduce the issue. Could you provide a screenshot of the resulting card you get from your config above? Maybe this helps. Thanks in advance!

**Comment by Zerosignal84** [comment]
> [@Zerosignal84](https://github.com/Zerosignal84), thanks for you bug report! It's hard for me to reproduce the issue. Could you provide a screenshot of the resulting card you get from your config above? Maybe this helps. Thanks in advance!

Yes of course, see below - let me know if you need anything further.

![Image](https://github.com/user-attachments/assets/e5c61b07-bb7f-41f5-9235-8d116497232d)

![Image](https://github.com/user-attachments/assets/a9bf582f-f6a6-4de9-88a1-3c8562b17813)

This if my full code:
```
type: custom:calendar-card-pro
entities:
  - entity: calendar.familycalendar
    label: mdi:human-male-female-child
    show_location: false
    show_time: true
    split_multiday_events: false
    blocklist: Swimming Classes
    compact_events_to_show: 5
  - entity: calendar.familycalendar
    allowlist: Swimming Classes
    compact_events_to_show: 1
days_to_show: 30
compact_events_to_show: 5
filter_duplicates: true
day_spacing: 3px
event_spacing: 3px
month_separator_width: 1px
today_indicator: pulse
weekday_font_size: 12px
day_font_size: 22px
show_month: false
show_countdown: true
show_progress_bar: true
time_icon_size: 12px
show_location: false
location_font_size: 10px
location_icon_size: 10px
weather:
  position: date
  date:
    show_conditions: true
    show_high_temp: true
    show_low_temp: true
    icon_size: 14px
    font_size: 12px
    color: var(--primary-text-color)
  event:
    show_conditions: true
    show_temp: true
    icon_size: 14px
    font_size: 12px
    color: var(--primary-text-color)
tap_action:
  action: navigate
  navigation_path: /dashboard-kitchenwallpanel/calendar?kiosk
hold_action:
  action: expand
height: 290px

```
