### ISSUE TITLE
[Bug]: Weird behaviour where calender pro goes outside section and overlays other sections

### ISSUE THREAD

**Issue by Deltids** [alexpfau/calendar-card-pro#233]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

![Image](https://github.com/user-attachments/assets/846481cc-edd6-4391-9df1-9af24f11765c)

```yaml
grid_options:
  columns: 12
  rows: 2
```

### Expected Behavior

![Image](https://github.com/user-attachments/assets/97aa9870-3033-4afe-87ba-cf42cbbd5700)

### Steps To Reproduce

1. Add calendar pro
2. Add another section below
3. Change number of rows on layout tab of calendar pro from 1 to 2

### Card Configuration

```yaml
entities:
  - calendar.lukas
days_to_show: 25
compact_days_to_show: 5
compact_events_complete_days: true
show_empty_days: true
show_past_events: true
weather:
  position: date
  date:
    show_conditions: true
    show_high_temp: true
    show_low_temp: false
    icon_size: 14px
    font_size: 12px
    color: var(--primary-text-color)
  event:
    show_conditions: true
    show_temp: true
    icon_size: 14px
    font_size: 12px
    color: var(--primary-text-color)
type: custom:calendar-card-pro
grid_options:
  columns: 12
  rows: 2
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: Chrome 136.0.7103.114
- Home Assistant Version: 2025.5.2 / 2025.05.1 / 15.2 / 20250516.0
- Calendar Card Pro Version: 3.0.5
- Device Type: raspberry pi 4
```

### Additional Information

See pictures and steps to reproduce. Removing the grid_options.rows (if present) will fix the issue.
