### ISSUE TITLE
[Feature]:

### ISSUE THREAD

**Issue by voyagers21** [alexpfau/calendar-card-pro#243]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've verified this feature isn't already available in the configuration options
- [x] I've searched existing issues to verify this hasn't already been requested

### Is your feature request related to a problem?

Bonjour Je souhaiterais mettre l'événement et l'heure de l'événement sur la même ligne

### Describe the solution you'd like

Je voudrais mettre la date de l'événement et l'événement sur la même ligne il était possible de le faire avec carte mode avant la dernière mise à jour mais depuis cela ne fonctionne plus,
quelqu'un a-t-il une solution?

### Example use case

Mettre l'événement et la date de l'événement sur la même ligne

**Comment by alexpfau** [comment]
You are right that this used to work, and card-mod is still the way to do it — the class names moved, which is almost certainly what broke your rule.

There is a maintained recipe for exactly this in the docs, kept in step with the card's markup: [Move time into the same row as the event title](https://calendar-card-pro.alexpfau.com/features/theming#move-time-into-the-same-row-as-the-event-title).

```yaml
type: custom:calendar-card-pro
entities:
  - calendar.family
card_mod:
  style: |
    div.event-content {
      display: grid;
      grid-template-areas:
        "title time"
        "location location";
      grid-template-columns: 1fr auto;
      column-gap: 10px;
      row-gap: 0px;
    }

    div.summary {
      grid-area: title;
      overflow: hidden;
      text-overflow: ellipsis;
    }

    div.time {
      grid-area: time;
      white-space: nowrap;
    }

    div.location {
      grid-area: location;
      white-space: normal;
      overflow: hidden;
      text-overflow: ellipsis;
    }

    div.time-location {
      display: contents;
    }
```

Closing as not planned as a built-in option. A config key would fix one arrangement, where the CSS above lets you put the title, time and location wherever you want them — and because the recipe lives in the docs it gets updated when the markup changes, which is the part that bit you here. If it does not work on your setup, comment and I will reopen.

Thanks also to @KonceptLabs for the nudge on the title.
