### ISSUE TITLE
[Feature]: Automatic Icon Mapping

### ISSUE THREAD

**Issue by countrock** [alexpfau/calendar-card-pro#244]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've verified this feature isn't already available in the configuration options
- [x] I've searched existing issues to verify this hasn't already been requested

### Problem
Currently, users need to manually add emojis to each calendar event in their calendar app to display icons. This becomes tedious for recurring events or when using multiple calendar sources.

### Proposed Solution
Add an `icon_mapping` configuration option that automatically displays icons based on keywords found in event titles.

### Benefits

- Cleaner calendar sources (no need to pollute event titles with emojis)
- Consistent iconography across different calendar apps
- Easy to maintain and update icon associations
- Works with imported/shared calendars where you can't edit titles

### Alternative Approaches

- Pattern matching (regex support)
- Category-based mapping
- Calendar-specific icon rules

### Example use case

```yaml
type: custom:calendar-card-pro
entities:
  - calendar.family
icon_mapping:
  swim: mdi:pool
  meeting: mdi:account-group
  birthday: mdi:cake
  garbage: mdi:delete-variant

### Additional context

_No response_

**Comment by alexpfau** [comment]
Thanks for this — and good news: what you are describing is already possible today, on the version you have. It just is not documented, which is our fault rather than yours, and we are fixing that.

The card lets you list the same calendar more than once, and each block filters and styles independently. So a block per keyword, each with an icon as its label, gives you the mapping:

```yaml
type: custom:calendar-card-pro
entities:
  - entity: calendar.family
    allowlist: swim
    label: mdi:swim
  - entity: calendar.family
    allowlist: meeting
    label: mdi:briefcase
  - entity: calendar.family
    allowlist: birthday
    label: mdi:cake-variant
  - entity: calendar.family
    allowlist: garbage
    label: mdi:trash-can
  - entity: calendar.family
    blocklist: swim|meeting|birthday|garbage
```

The last block is the catch-all: it blocks every term the blocks above match, so it carries everything else and leaves those events without an icon. Give it a `label` of its own if you would rather have a fallback icon than none.

`label` reads an `mdi:` value as an icon automatically, so there is no second option to set. Each block can also carry its own `color`, `accent_color` and so on, if you want the swim events styled differently as well as iconified.

One thing worth knowing if your titles can match two patterns at once — say an event called "Swim meeting". By default it would appear under both blocks, once each. Adding `filter_duplicates: true` at the card level collapses that to a single row, and the block listed first wins, so the order of your blocks becomes the priority order in the same way a mapping table's first match would.

This meets the goals you listed — no emojis in the calendar itself, consistent icons across sources, and it works on calendars you cannot edit. What it does not do is give you a compact table, and we understand why you asked for one. We have decided against adding `icon_mapping` as a separate option, because it would overlap heavily with the allowlist and blocklist that already decide which events a block matches, and having two places that answer "which events get treated how" tends to make both harder to reason about. In YAML the block form is a few lines you copy and adjust, which we think is a fair trade for not adding a second filtering vocabulary to the card.

We are adding this exact example to the documentation so the next person finds it without having to ask.
