### ISSUE TITLE
[Bug]: Custom Element Doesn't Exist: calendar-card-pro

### ISSUE THREAD

**Issue by i-am-the-arm** [alexpfau/calendar-card-pro#250]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

Hello,

It's possible my ipad/browser is too old but wanted to confirm in case there's a possible solution. When adding this card to my dashboard, I'm getting the error: `Custom Element Doesn't Exist: calendar-card-pro` on the ipad with the configuraiton in red within the error body. This only happens on the iPad, iPhone and laptop work fine.

edit: turns out this may be a home-assistant thing in general rather than specific to this repo. please confirm

Thanks!

### Expected Behavior

Should show card

### Steps To Reproduce

See description

### Card Configuration

```yaml
- type: grid
        cards:
          - entities:
              - entity: calendar.family
                label: mdi:human-male-female-child
                color: ''
              - entity: calendar.me
                label: mdi:human-male
              - entity: calendar.spouse
                show_time: false
                label: mdi:human-female
            days_to_show: 2
            weather:
              position: event
              date:
                show_conditions: true
                show_high_temp: true
                show_low_temp: false
                icon_size: 14px
                font_size: 12px
                color: var(--primary-text-color)
              event:
                show_conditions: true
                show_temp: true
                icon_size: 14px
                font_size: 12px
                color: var(--primary-text-color)
              entity: weather.forecast_home
            type: custom:calendar-card-pro
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: IOS/Safari 12.5.7
- Home Assistant Version: 2025.5.3
- Calendar Card Pro Version: 3.0.6
- Device Type: iPad Mini 2
```
