### ISSUE TITLE
[Bug]: Weather minimum temperature not displayed if it's zero degrees

### ISSUE THREAD

**Issue by DaveOzzie** [alexpfau/calendar-card-pro#252]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

The minimum temperature not displayed if it's zero degrees, other values (-1 etc) are displayed correctly.
![Image](https://github.com/user-attachments/assets/9d4d3075-3814-4d69-8f04-e3284f5af3d0)

### Expected Behavior

zero defrees should be displayed.

### Steps To Reproduce

Needs a daily weather minimum temperature to be zero.

### Card Configuration

```yaml
entities:
  - entity: calendar.daveozzie
days_to_show: 7
compact_days_to_show: 3
compact_events_complete_days: true
show_empty_days: true
show_location: false
weather:
  position: date
  date:
    show_conditions: true
    show_high_temp: true
    show_low_temp: true
    icon_size: 14px
    font_size: 12px
    color: var(--primary-text-color)
  event:
    show_conditions: true
    show_temp: true
    icon_size: 14px
    font_size: 12px
    color: var(--primary-text-color)
  entity: weather.bom
tap_action:
  action: expand
type: custom:calendar-card-pro
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: 
- Home Assistant Version: 
- Calendar Card Pro Version: 
- Device Type:
```
