### ISSUE TITLE
[Bug]: show_past_events overrides show_time

### ISSUE THREAD

**Issue by tcpr1** [alexpfau/calendar-card-pro#255]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

When I set show_past_event: true and start_date: "-1", it disables show_time

![Image](https://github.com/user-attachments/assets/8bccf51c-0c62-4187-be5a-26d47131e38f)

![Image](https://github.com/user-attachments/assets/747d8aa7-5c6b-4678-926e-a69874834a75)

### Expected Behavior

show_past_event: true should not impact the show_time feature.

### Steps To Reproduce

add a card and paste card configuration

### Card Configuration

```yaml
entities:
  - calendar.mycalendar
start_date: "-1"
days_to_show: 7
compact_events_to_show: 2
show_month: false
**show_past_events: true**
type: custom:calendar-card-pro
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: latest chrome
- Home Assistant Version: 20250531.3
- Calendar Card Pro Version: v.3.0.6
- Device Type: desktop
```
