### ISSUE TITLE
[Bug]: RTL Language event alignment

### ISSUE THREAD

**Issue by dmatik** [alexpfau/calendar-card-pro#259]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

Hi,
It seems that there few alignment issues when using with RTL language.

1. The vertical line is on the left side of the even instead of the right side.
2. The space between time icon and time is smaller.
3. The time is vertically not aligned with the time icon. 

Please see image attached.

![Image](https://github.com/user-attachments/assets/491fba13-f565-48f6-9211-d03dbf7d4e17)

### Expected Behavior

1. The vertical line is on the right side.
2. The space between time icon and time is same as in LTR languages.
3. The time is vertically aligned with the time icon. 

### Steps To Reproduce

1. Add Calendar Pro card to the dashboard.
2. Change HA language in profile to any RTL language.
3. Make sure events are displayed on the card.

### Card Configuration

```yaml
entities:
  - calendar.home
days_to_show: 14
compact_days_to_show: 14
compact_events_to_show: 5
vertical_line_width: 1px
day_spacing: 4px
event_spacing: 6px
day_separator_width: 1px
day_font_size: 18px
show_month: false
time_24h: true
time_font_size: 14px
time_icon_size: 16px
show_location: false
weather:
  position: date
  date:
    show_conditions: true
    show_high_temp: true
    show_low_temp: false
    icon_size: 14px
    font_size: 12px
    color: var(--primary-text-color)
  event:
    show_conditions: true
    show_temp: true
    icon_size: 14px
    font_size: 12px
    color: var(--primary-text-color)
type: custom:calendar-card-pro
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: 
- Home Assistant Version: 
- Calendar Card Pro Version: 
- Device Type:
```
