### ISSUE TITLE
[Bug]: Wrong date for event

### ISSUE THREAD

**Issue by kummerr** [alexpfau/calendar-card-pro#28]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

The card is showing the event the day before the actual calendar event. For example March 17th is St Patrick's day in the US. Calendar-card-pro is listing the event as March 16. This same error is occurring  with all of my calendars.

If I check the calendar: get events in developer tools  actions I get the following response for March 17th:

`calendar.holidays_in_united_states:
  events:
    - start: "2025-03-17"
      end: "2025-03-18"
      summary: St. Patrick's Day
      description: >-
        Observance

        To hide observances, go to Google Calendar Settings > Holidays in United
        States

March 16th yields the follow response:
`calendar.holidays_in_united_states:
  events: []

Could this be a timezone issue? What time does the card query for the date? I'm using MDT for my current timezone if that helps. 

### Expected Behavior

Card to list the correct date for an event.
`

### Steps To Reproduce

1. Install calendar card pro using HACS
2. Add calendar card pro to dashboard
3. Configure using guide from github

### Card Configuration

```yaml
type: custom:calendar-card-pro
entities:
  - entity: calendar.family
    color: "#f44336"
  - entity: calendar.garbage_day
    color: "#44af14"
  - entity: calendar.holidays_in_united_states
    color: "#ffffff"
  - entity: calendar.personal_calendar
    color: "#f44336"
  - entity: calendar.recycling_collection
    color: "#3d85c6"
days_to_show: 10
max_events_to_show: 10
show_past_events: false
language: en
time_24h: false
show_end_time: false
show_month: true
show_location: true
remove_location_country: true
title: 📅 Upcoming Events
background_color: "#00000"
row_spacing: 10px
additional_card_spacing: 0px
vertical_line_width: 0px
vertical_line_color: "#baf1ff"
horizontal_line_width: 3px
horizontal_line_color: "#baf1ff80"
title_font_size: 26px
weekday_font_size: 14px
day_font_size: 32px
month_font_size: 12px
event_font_size: 14px
time_font_size: 12px
location_font_size: 12px
time_location_icon_size: 14px
title_color: "#ffff"
weekday_color: "#fffff"
day_color: "#fffff"
month_color: fffff
event_color: "#baf1ff"
time_color: "#baf1ff"
location_color: "#baf1ff"
refresh_interval: 15
tap_action:
  action: expand
hold_action:
  action: navigate
  navigation_path: calendar
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: Google Chrome Version 134.0.6998.89 (Official Build) (x86_64)
- Home Assistant Version: 025.3.3
- Calendar Card Pro Version: 1.0.0
- Device Type: MacBook Pro, iPad and iPhone
```
