### ISSUE TITLE
[Feature]: Filter Events

### ISSUE THREAD

**Issue by hlymn231** [alexpfau/calendar-card-pro#32]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've verified this feature isn't already available in the configuration options
- [x] I've searched existing issues to verify this hasn't already been requested

### Is your feature request related to a problem?

No

### Describe the solution you'd like

I'd like to have a option to filter out events based on event words. I.e. a name or specific events like "trash day". 

### Example use case

entities:
  - entity: calendar.family
    name: Family
    blocklist: (John)|(Trash Day)

Here is a example based on another calendar list I use

**Comment by pgaida** [comment]
I also welcome this proposal.

**Comment by AndreiGavriliu** [comment]
This would be awesome. I have some events which are not relevant for my HA dashboard, but I need in my calendar on my phone, for example.

**Comment by netsoft-ruidias** [comment]
My proposal here: https://github.com/alexpfau/calendar-card-pro/issues/110

I was here to make exactly this feature request, I would love to see this integrated...

I'm moving away from `atomic-calendar-revive` in favor of this, in `atomic-calendar-revive` you can add a fantastic property called `blocklist`, which allows you to exclude certain events that have that word or list of words: ex: 
```yaml
type: custom:atomic-calendar-revive
entities:
  - entity: calendar.xxx_yyy
    color: "#2d89ef"
    name: My Calendar
    icon: mdi:cake-variant
    blocklist: (Vacation)|(Holiday)|(Birthday)
```
in this example above, I would exclude all events that contain one of the words indicated by `exclude`

### Nice to Have

In addition to the possibility of excluding, displaying everything else, it would be interesting to also have the opposite, that is, the possibility of only including, excluding everything else, for example:

```yaml
  - entity: calendar.xxx_yyy
    accent_color: "#43a047"
    label: 👪
    blocklist: (Vacation)|(Holiday)|(Birthday)
  - entity: calendar.xxx_yyy
    accent_color: "#ead196"
    label: 🎂
    includeOnly: (Birthday)
  - entity: calendar.xxx_yyy
    accent_color: "#43a047"
    label: 🌴
    includeOnly: (Vacation)|(Holiday)
```
