### ISSUE TITLE
[Bug]: Default language is not system language

### ISSUE THREAD

**Issue by tonka3000** [alexpfau/calendar-card-pro#36]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

Hi, 

Thanks for the amazing card.

My system is set to German (Austria) but the language I got in the card is English. I can only change it when I set the language in the card to de.

I assume that the detection for Austrian German does not work.

Greetings
Michael

### Expected Behavior

The card should use de language on Austria German language setting.

### Steps To Reproduce

-

### Card Configuration

```yaml
type: custom:calendar-card-pro
entities:
  - entity: calendar.tonks
days_to_show: 5
show_location: true
tap_action:
  action: more-info
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: 
- Home Assistant Version: 
- Calendar Card Pro Version: 
- Device Type:
```
