### ISSUE TITLE
[Feature]: Time and title on same line

### ISSUE THREAD

**Issue by perolamlarsson** [alexpfau/calendar-card-pro#37]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've verified this feature isn't already available in the configuration options
- [x] I've searched existing issues to verify this hasn't already been requested

### Is your feature request related to a problem?

I'm not using location and my title of events are always rather short. Having title and time/duration on two different rows create a lot of blank and unused space to the right of the text. 

### Describe the solution you'd like

I would like the option to have the title after the time/duration on the same line

### Example use case

A parameter option on what should be on what line in each calendar entry

**Comment by Symbiot78** [comment]
Agreed and 2nd. 
For me it's mostly to save space.
I use atomic atm. and have everything in one line it would be grand to be able to do this for calendar card pro. 
Not that I just want a copy of atomic - I dig the features of calendar card pro :)

like this:

![Image](https://github.com/user-attachments/assets/7b131752-50f3-4562-9c5c-dbd9d833da89)

**Comment by vichjiri** [comment]
Hi, I have similar need, my reason is mainly to save space, because I usually have many events in one day 🙏 

Like this:
<img width="339" alt="Image" src="https://github.com/user-attachments/assets/890546da-3737-4318-b20e-822dd5f67f02" />

**Comment by perolamlarsson** [comment]
Did a quick check and it seems to work. Will look into details later. Thanks

**Comment by alexpfau** [comment]
@perolamlarsson, thanks for your feature request and sorry for the delayed response.

At least at this point, I will not implement your request as a native feature. The reason is that there are many complexities to consider, e.g. how this setting interacts with countdown and progress bar, which may require additional parameters to serve different user's needs. Therefore, at least for now, I will not natively implement this.

However, I will add your feature request as another card-mod example to my ReadMe. @sevorl has provided a great card-mod configuration already. Here's a refined version to (a) move the time to the same row as the event title, aligned to the right, while (b) keep the location row underneath. This comes very close to how I'd implement this feature natively.

Here is the card-mod config I will add to the ReadMe:

```yaml
card_mod:
  style: |
    div.event-content {
      display: grid;
      grid-template-areas: 
        "title time"
        "location location";
      grid-template-columns: 1fr auto;
      column-gap: 10px;
      row-gap: 0px;
    }
    
    div.summary {
      grid-area: title;
      overflow: hidden;
      text-overflow: ellipsis;
    }
    
    div.time {
      grid-area: time;
      white-space: nowrap;
    }
    
    div.location {
      grid-area: location;
      white-space: normal;
      overflow: hidden;
      text-overflow: ellipsis;
    }
    
    div.time-location {
      display: contents;
    }
```
