### ISSUE TITLE
[Feature]: Inherit event color from the Google Calendar Event

### ISSUE THREAD

**Issue by swampylee** [alexpfau/calendar-card-pro#52]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've verified this feature isn't already available in the configuration options
- [x] I've searched existing issues to verify this hasn't already been requested

### Is your feature request related to a problem?

Not related to a problem

### Describe the solution you'd like

I'd like the ability for this card to allow each agenda item to inherit the background color of the event from whatever is used/defined in Google Calendar.

### Example use case

![Image](https://github.com/user-attachments/assets/8f243627-d29c-4f0d-a0d4-3da2fc99a50a)

**Comment by Misiu** [comment]
do the events that come from Google Calendar have the colors?
call `calendar.get_events` action in the developer tools.
for example:
```
action: calendar.get_events
data:
  start_date_time: "2025-03-18 00:00:00"
  end_date_time: "2025-06-21 00:00:00"
target:
  entity_id: calendar.zmieszane
```

In my case I get this response:
```
calendar.zmieszane:
  events:
    - start: "2025-03-24"
      end: "2025-03-25"
      summary: Zmieszane
      description: ""

```

So I think it will be hard to pick color from Google Calendar if the event doesn't store that color
