### ISSUE TITLE
[Bug]: fr language not working

### ISSUE THREAD

**Issue by marc3k18** [alexpfau/calendar-card-pro#59]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

Hello,

Setting language to fr is not working.

I'm still getting the date and month in english.

Thanks!

### Expected Behavior

Have the day name in french

### Steps To Reproduce

Add the language: fr

### Card Configuration

```yaml
type: custom:calendar-card-pro
entities:
  - hiden
days_to_show: 5
show_location: true
language: fr
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: Lastest Android HA and Chrome
- Home Assistant Version: 2025.3.4
- Calendar Card Pro Version: Lastest
- Device Type: Android Tablet and Windows pc.
```
