### ISSUE TITLE
[Bug]: max_events_to_show not limiting to 2

### ISSUE THREAD

**Issue by bvweerd** [alexpfau/calendar-card-pro#64]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

max_events_to_show is not limiting the amount of events if the amount of planned events on a single day is bigger.

So e.g. limit = 2, events on a day is 3, then it shows 3
e.g. limit = 3, events on day 1 = 2, events on day 2 is 2, then it shows 4. 

The Configuration:
```
type: custom:calendar-card-pro
entities:
  - calendar.agenda
days_to_show: 2
show_location: false
day_font_size: 14x
weekday_font_size: 14px
month_font_size: 10px
title_font_size: 10px
max_events_to_show: 2
show_month: false
language: nl
```

![Image](https://github.com/user-attachments/assets/0e514047-c217-4fa6-897c-a98d3fe4487d)

Version used: v.1.2.0

### Expected Behavior

Limit to max_events_to_show although there are more events on a single day

### Steps To Reproduce

1. add multiple events to multiple days
2. play around with max_events_to_show

### Card Configuration

```yaml
type: custom:calendar-card-pro
entities:
  - calendar.agenda
days_to_show: 2
show_location: false
day_font_size: 14x
weekday_font_size: 14px
month_font_size: 10px
title_font_size: 10px
max_events_to_show: 2
show_month: false
language: nl
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: Firefox 136.0.1 (64-bit)
- Home Assistant Version: 2025.3.3
- Calendar Card Pro Version: v1.2.0
```
