### ISSUE TITLE
[Bug]: Scrollbar in v2.0

### ISSUE THREAD

**Issue by Misiu** [alexpfau/calendar-card-pro#97]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

I get a scrollbar for the card:

![Image](https://github.com/user-attachments/assets/2805bb53-fb64-449a-b0dc-7eec3afc12cc)

![Image](https://github.com/user-attachments/assets/4525d261-1a94-4a8a-b43f-22cc70649dc9)

### Expected Behavior

There shouldn't be a scrollbar, it wasn't there previously

### Steps To Reproduce

1. Update the card to the latest version

### Card Configuration

```yaml
type: custom:calendar-card-pro
entities:
  - entity: calendar.szklo
    color: "#008F00"
    show_end_time: false
  - calendar.papier
  - calendar.plastik_i_metal
  - entity: calendar.zmieszane
    accent_color: "#00ffff"
    show_time: false
days_to_show: 20
show_location: true
show_end_time: false
vertical_line_width: 4px
```

### Calendar Entity State

```yaml

```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: Chrome 134
- Home Assistant Version: 2025.3.4
- Calendar Card Pro Version: 2.0.0
- Device Type: PC
```
